### ISSUE TITLE
Use phpQuery via composer

### ISSUE THREAD

**Issue by Page-** [smrealms/smr#107]
https://packagist.org/packages/electrolinux/phpquery

**Comment by hemberger** [comment]
I have a PR ready for this, but I just wanted to make sure you don't mind that `electrolinux` isn't an "official" phpQuery repository (though to be fair, there is _no_ official phpQuery since Tobias' 0.9.5 version).

**Comment by Page-** [comment]
Yeah, it's the one I linked in the issue :P  But it looks like it's the true "official" version now (like libreoffice took over from openoffice)
