### ISSUE TITLE
Upgrade to php7

### ISSUE THREAD

**Issue by hemberger** [smrealms/smr#110]
The current `Dockerfile` uses php 5.4, which has already reached [end of life](http://php.net/supported-versions.php). We should switch to 5.6 as soon as possible, which, while active support was dropped in Jan 2017, security support will continue until the end of 2018. I have extensively tested the game, Caretaker, and NPC's with 5.6 and have found no incompatibilities, so I'd be happy to see the upgrade immediately (I'd be happy to provide a PR if desired).

However, we'd be well advised to upgrade to php 7+, which I am beginning to test now. One of the biggest changes that needs to be made is migrating to a new MySQL API, since `php-mysql` was deprecated in php 5.5. [Here](http://php.net/manual/en/mysqlinfo.api.choosing.php) are some considerations to help choose between `PDO` and `mysqli`. Are there any preferences?

**Comment by hemberger** [comment]
If we continue to use `runkit` in the NPC script, it looks like we won't be able to upgrade to php7 yet. The only php7-supported version of runkit seems to be [runkit7/runkit7](https://github.com/runkit7/runkit7), but in its documentation, it says that the only function we use (`runkit_constant_redefine` for `TIME` and `MICROTIME`) is unsupported.
```
Unsupported APIs for PHP7:
runkit_constant_* : runkit_constant_add works reliably, other methods don't. This works better when the constants are declared in a different file.
```
We can always replace `TIME` and `MICROTIME` with variables (and I would be happy to do that if it was our best option), but at this time we're not able to upgrade.

**Comment by hemberger** [comment]
I found some additional libraries that can modify constants without the heavy machinery of runkit (e.g. [soft-mocks](https://github.com/badoo/soft-mocks/commits/master)). So we have a few options:
1. Replace `TIME` and `MICROTIME` with variables
2. Wait to see if runkit (or some close variant) achieves support of `runkit_constant_redefine`
3. Experiment with soft-mocks now

Any preferences?

**Comment by Page-** [comment]
I think using them as $TIME and $MICROTIME would work, just have to make sure nothing other than the NPC script reassigns them
