### ISSUE TITLE
Universe generation not working correctly?

### ISSUE THREAD

**Issue by regnighc** [smrealms/smr#1249]
I'm generating the universe/game but it does not generate any Planets, Ports or Warps.

Is this normal behaviour ? it seems like a huge task to manually add all of these.

**Comment by hemberger** [comment]
Thanks for the question! Currently, it does generate an empty universe, but I'd be happy to add an option to auto-populate the map, if that would be useful. Once you have a specific design in mind for a map, you'll probably want a clean slate, but I can definitely see the utility if you're just starting out.
