### ISSUE TITLE
Versioning CSS files

### ISSUE THREAD

**Issue by hemberger** [smrealms/smr#139]
I have hesitated to make improvements to the CSS because of caching. It would be nice to implement a strategy that will ensure the new CSS files are downloaded if they happen to change. The most canonical way I know to do this is to add a version number to the CSS link, which tricks the browser into downloading it, even though the actual path of the file has not changed.

See https://stackoverflow.com/questions/7671168/why-adding-version-number-to-css-file-path.

Any objections to this approach?

**Comment by Page-** [comment]
Nope, it's fine by me, it'd just be nice if it was done automatically as part of a build system that also handles the minification of the js/css, and could use a hash of the contents of the version number, in order to not cache bust when it doesn't need to
