### ISSUE TITLE
Ship Details from Current Sector (Tool tip) + Remove Examine Screen

### ISSUE THREAD

**Issue by Red-Cross-Knight** [smrealms/smr#31]
2 Part change
Ref: http://smrcnn.smrealms.de/viewtopic.php?f=102&t=11443

Part 1:
Ship details (same as what is displayed in examine screen current) displayed in a tool tip.  Will need tested for performance. 

Location: Possible a "Info" button?

Part 2:  Remove examine screen, replace "Examine" button with "Attack".

**Comment by wcyrek** [comment]
This is moved to beta as smr 2.0 feature.
