### ISSUE TITLE
Changes to Racial Councils

### ISSUE THREAD

**Issue by Red-Cross-Knight** [smrealms/smr#53]
Ref: http://smrcnn.smrealms.de/viewtopic.php?f=94&t=11675

Following changes to be made:
1. Council size = 5
2. Relation change increased from +-10 to +-15
3. Vote length changed to 48 hours (if possible make vote length based on game speed;which would actually put 1.5x at 54 hours)
4. Veto time should = vote time - 24 hours

Further clarification,  please refer to thread or contact Jouldax.

**Comment by hemberger** [comment]
1. Done
2. Effectively done (PR #295 means that relations can change twice as fast)
3. Not implemented (as per Page's comments)
4. Not implemented (hasn't been any further request for this in the past 5 years)
