### ISSUE TITLE
Question about color options in Account Preferences

### ISSUE THREAD

**Issue by hemberger** [smrealms/smr#66]
There appear to be three new color options in Account Preferences (Friendly, Neutral, and Enemy). I assumed that these would apply to the Trader icons on the Local Map. But when I change these color options, I cannot identify anything in the game that is changing. What are these options supposed to change?

By the way, I am color-blind, so the prospect of customizing colors is very exciting!

**Comment by Page-** [comment]
Yes, these should be referring to trader (and force) icons on the local/galaxy maps

**Comment by wcyrek** [comment]
Fix pushed live
