### ISSUE TITLE
CSRF state token does not match one provided

### ISSUE THREAD

**Issue by MichaelKunze** [smrealms/smr#67]
There might be a problem with the login_processing.php and Facebook.

I'm getting alot of those in my server log:

2014/10/27 04:03:31 [error] 17076#0: *4093313 FastCGI sent in stderr: "PHP message: CSRF state token does not match one provided" while reading response header from upstream, client: xxx.xxx.xxx.xxx, server: www.smrealms.de, request: "GET /login_processing.php?loginType=Facebook&code=XXXXXXX&state=XXXXXX HTTP/1.1", upstream: "fastcgi://unix:/some/path/php5-fpm.sock:", host: "www.smrealms.de", referrer: "https://www.facebook.com/dialog/oauth?client_id=XXXXX&redirect_uri=https%3A%2F%2Fwww.smrealms.de%2Flogin_processing.php%3FloginType%3DFacebook&state=XXXXX&scope=email"

**Comment by hemberger** [comment]
As of bb09c388de98e9c5cc384444c1011586342515f2, we install the Facebook SDK with composer, rather than including the source code directly. This should avoid Facebook login-related errors, but please re-open if it becomes an issue again.
