### ISSUE TITLE
Use dynamically generated radar charts to display race strengths

### ISSUE THREAD

**Issue by hemberger** [smrealms/smr#919]
On the "Join Game" page, we have gifs that define a numerical strength for each race in 4 different categories, e.g.

![image](https://user-images.githubusercontent.com/846186/99318858-62b31c00-281d-11eb-9a81-854b34670935.png)

This is not maintainable, because these gifs are hard-coded and we cannot update the numerical values. As the balance between races changes, these graphs will become more and more out of date.

However, we could use d3js or Plotly to dynamically generate these graphics, and even animate them. See for example:
d3js: http://bl.ocks.org/tpreusse/2bc99d74a461b8c0acb1
plotly: https://plotly.com/javascript/radar-chart/

**Comment by witold-cyrek** [comment]
I want to implement this usign Highcharts because it's by far easiest.

**Comment by hemberger** [comment]
Have you looked at plotly? It's FOSS and at a quick glance looks about as simple as HighCharts. Since I have prior (and continuing) experience with Plotly, it's something I would be comfortable maintaining. I'm a bit worried about the licensing aspect of HighCharts. Right now, we probably would be considered "non-commercial", but I don't know if that is/will always be the case.

**Comment by witold-cyrek** [comment]
I can try with plotly.  It will take more research thou, their documentations turns it into a case of trial and error to get the look I need.

**Comment by witold-cyrek** [comment]
I'm done but it looks largely terrible becase there is scant documentation for radialaxis, and no visible way to change the background color, so it is white.  When people complain we can change libraries :)
